// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqaurutlyhqlgcbfsgba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxYXVydXRseWhxbGdjYmZzZ2JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4Mzk4ODcsImV4cCI6MjA3MDQxNTg4N30.y7xOUZSzvrfmC5B4AjQFvwbfefCkHvTKX3hn9ULOfns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});